---
env:
  es6: true,
parserOptions:
  ecmaVersion: 6
  sourceType: 'script'
globals:
  window: true
  $: true
  document: true
  _: true
  console: true
  process: true
  fetch: true
  module: true
  require: true
rules:
  comma-dangle: 0
  no-cond-assign: 1
  no-constant-condition: 1
  no-control-regex: 1
  no-debugger: 2
  no-dupe-args: 1
  no-dupe-keys: 1
  no-duplicate-case: 1
  no-empty-character-class: 1
  no-empty: 1
  no-ex-assign: 1
  no-extra-boolean-cast: 1
  no-extra-parens: 0
  no-extra-semi: 1
  no-func-assign: 1
  no-inner-declarations: 1
  no-invalid-regexp: 1
  no-irregular-whitespace: 1
  no-negated-in-lhs: 1
  no-obj-calls: 1
  no-regex-spaces: 1
  no-sparse-arrays: 1
  no-unreachable: 1
  use-isnan: 1
  valid-jsdoc: 0
  valid-typeof: 1
  no-unexpected-multiline: 1
  accessor-pairs: 1
  block-scoped-var: 1
  complexity: 1
  consistent-return: 0
  curly: 1
  default-case: 1
  dot-notation: 0
  dot-location: 0
  eqeqeq: 2
  guard-for-in: 1
  no-alert: 0
  no-caller: 1
  no-div-regex: 1
  no-else-return: 0
  no-labels: 1
  no-eq-null: 1
  no-eval: 1
  no-extend-native: 1
  no-extra-bind: 1
  no-fallthrough: 1
  no-floating-decimal: 1
  no-implicit-coercion: 0
  no-implied-eval: 1
  no-invalid-this: 1
  no-iterator: 1
  no-lone-blocks: 1
  no-loop-func: 1
  no-multi-spaces: 0
  no-multi-str: 1
  no-native-reassign: 1
  no-new-func: 1
  no-new-wrappers: 1
  no-new: 1
  no-octal-escape: 1
  no-octal: 1
  no-param-reassign: 1
  no-process-env: 1
  no-proto: 1
  no-redeclare: 1
  no-return-assign: 1
  no-script-url: 1
  no-self-compare: 1
  no-sequences: 0
  no-throw-literal: 1
  no-unused-expressions: 1
  no-useless-call: 1
  no-useless-concat: 1
  no-void: 1
  no-warning-comments: 1
  no-with: 1
  radix: 1
  vars-on-top: 0
  wrap-iife: 0
  yoda: 1
  init-declarations: 0
  no-catch-shadow: 1
  no-delete-var: 1
  no-label-var: 1
  no-shadow-restricted-names: 1
  no-shadow: 2
  no-undef-init: 1
  no-undef: 1
  no-undefined: 0
  no-unused-vars: 1
  no-use-before-define: 0
  array-bracket-spacing: 1
  block-spacing: 0
  brace-style: 0
  camelcase: 0
  comma-spacing: 0
  comma-style: 1
  computed-property-spacing: 1
  consistent-this: 0
  eol-last: 0
  func-names: 0
  func-style: [0, 'expression']
  id-length: 0
  id-match: 1
  indent: [0, 2]
  jsx-quotes: 0
  key-spacing: 0
  lines-around-comment: 1
  linebreak-style: 1
  max-nested-callbacks: 1
  new-cap: 0
  new-parens: 1
  newline-after-var: 0
  no-array-constructor: 1
  no-continue: 1
  no-inline-comments: 0
  no-lonely-if: 1
  no-mixed-spaces-and-tabs: 1
  no-multiple-empty-lines: 0
  no-nested-ternary: 1
  no-new-object: 1
  no-restricted-syntax: 1
  no-spaced-func: 0
  no-ternary: 0
  no-trailing-spaces: 0
  no-underscore-dangle: 0
  no-unneeded-ternary: 0
  object-curly-spacing: 0
  one-var: 0
  operator-assignment: 1
  operator-linebreak: 1
  padded-blocks: 0
  quote-props: 0
  quotes: 0
  require-jsdoc: 0
  semi-spacing: 0
  semi: 0
  sort-vars: 0
  space-after-keywords: 0
  space-before-keywords: 0
  space-before-blocks: 0
  space-before-function-paren: 0
  space-in-parens: 1
  space-infix-ops: 0
  keyword-spacing: 1
  space-unary-ops: 1
  spaced-comment: 0
  wrap-regex: 1
